### ISSUE TITLE
Asset dump

### ISSUE THREAD

**Issue by zpl-zak** [MafiaHub/awesome-mafia#1]
Use this space to store archives for the Mafia modding tools and resources only.

**Comment by zpl-zak** [comment]
[Mafcapone.cl-1.zip](https://github.com/user-attachments/files/16227907/Mafcapone.cl-1.zip)

**Comment by zpl-zak** [comment]
Closed on purpose but will be kept for asset dumps.

**Comment by Richard01CZ** [comment]
[
[MSDR CZ.pdf](https://github.com/user-attachments/files/16228218/MSDR.CZ.pdf)
](url)

**Comment by Richard01CZ** [comment]
[mafia_patch_1.1_pol.exe.zip](https://github.com/user-attachments/files/16235053/mafia_patch_1.1_pol.exe.zip)
[mafia_patch_1-1_eng.zip](https://github.com/user-attachments/files/16235055/mafia_patch_1-1_eng.zip)
[mafia_patch_1-1_fre.zip](https://github.com/user-attachments/files/16235061/mafia_patch_1-1_fre.zip)
[mafia_patch_1-1_ger.zip](https://github.com/user-attachments/files/16235072/mafia_patch_1-1_ger.zip)
Patches 1.1

**Comment by Richard01CZ** [comment]
[mafia_patch_1.1_pol.zip](https://github.com/user-attachments/files/16235151/mafia_patch_1.1_pol.zip)
Polish patch without .exe in zip name

**Comment by Richard01CZ** [comment]
[mafia_patch_1.2_bra.zip](https://github.com/user-attachments/files/16235211/mafia_patch_1.2_bra.zip
[mafia_patch_1.2_fre.zip](https://github.com/user-attachments/files/16235234/mafia_patch_1.2_fre.zip)
)
[mafia_patch_1.2_cze.zip](https://github.com/user-attachments/files/16235218/mafia_patch_1.2_cze.zip
[mafia_patch_1.2_jap.zip](https://github.com/user-attachments/files/16235253/mafia_patch_1.2_jap.zip)
[mafia_patch_1.2_pol.zip](https://github.com/user-attachments/files/16235258/mafia_patch_1.2_pol.zip)
[mafia_patch_1.2_spa.zip]([mafia_patch_1.3_eng.zip](https://github.com/user-attachments/files/16235345/mafia_patch_1.3_eng.zip))
)
[mafia_patch_1.2_eng.zip](https://github.com/user-attachments/files/16235226/mafia_patch_1.2_eng.zip)
[mafia_patch_1.2_ger.zip](https://github.com/user-attachments/files/16235245/mafia_patch_1.2_ger.zip)
[mafia_patch_1.2_ita.zip](https://github.com/user-attachments/files/16235250/mafia_patch_1.2_ita.zip)

1.2 and 1.3 patches

**Comment by Richard01CZ** [comment]
[Project_Angelo_script_inspector.zip](https://github.com/user-attachments/files/16238313/Project_Angelo_script_inspector.zip)

[TACO-M.zip](https://github.com/user-attachments/files/16238359/TACO-M.zip)

**Comment by Richard01CZ** [comment]
[3D Model List.zip](https://github.com/user-attachments/files/16238692/3D.Model.List.zip)

**Comment by Richard01CZ** [comment]
[navod_cutsceny.pdf](https://github.com/user-attachments/files/16238732/navod_cutsceny.pdf)
[zaklady_zmodeleru.pdf](https://github.com/user-attachments/files/16238734/zaklady_zmodeleru.pdf)

**Comment by Richard01CZ** [comment]
[CSVtoDef.zip](https://github.com/user-attachments/files/16238771/CSVtoDef.zip)

**Comment by Richard01CZ** [comment]
[MafiaDataXTractor.zip](https://github.com/user-attachments/files/16238944/MafiaDataXTractor.zip)

**Comment by Richard01CZ** [comment]
[BScriptView Collection.zip](https://github.com/user-attachments/files/16255201/BScriptView.Collection.zip)

**Comment by Richard01CZ** [comment]
[TreeRE Collection.zip](https://github.com/user-attachments/files/16255223/TreeRE.Collection.zip)

**Comment by Richard01CZ** [comment]
[Mafia DTA Extractor.zip](https://github.com/user-attachments/files/16255367/Mafia.DTA.Extractor.zip)

**Comment by Richard01CZ** [comment]
[BScriptView 6.0.pdf](https://github.com/user-attachments/files/16255436/BScriptView.6.0.pdf)
[Mr Robville's Model Implementation Guide (2015).pdf](https://github.com/user-attachments/files/16255438/Mr.Robville.s.Model.Implementation.Guide.2015.pdf)

**Comment by Richard01CZ** [comment]
[Empty_Mission.zip](https://github.com/user-attachments/files/16255595/Empty_Mission.zip)

**Comment by Richard01CZ** [comment]
[4ds Converter (2004).zip](https://github.com/user-attachments/files/16267266/4ds.Converter.2004.zip)
[4ds Distance Fix (2007).zip](https://github.com/user-attachments/files/16267267/4ds.Distance.Fix.2007.zip)
[4ds From PS2 Converter.zip](https://github.com/user-attachments/files/16267269/4ds.From.PS2.Converter.zip)
[4ds Manager Textures.zip](https://github.com/user-attachments/files/16267271/4ds.Manager.Textures.zip)
[4ds Sector Cleaner.zip](https://github.com/user-attachments/files/16267273/4ds.Sector.Cleaner.zip)
[4ds Unlocker.zip](https://github.com/user-attachments/files/16267274/4ds.Unlocker.zip)
[4ds View v8.3.zip](https://github.com/user-attachments/files/16267276/4ds.View.v8.3.zip)
[5ds Converter v1.1.zip](https://github.com/user-attachments/files/16267277/5ds.Converter.v1.1.zip)

**Comment by Richard01CZ** [comment]
[Boz 4ds Full Manager.zip](https://github.com/user-attachments/files/16267681/Boz.4ds.Full.Manager.zip)
[Boz Scene Tree Editor.zip](https://github.com/user-attachments/files/16267683/Boz.Scene.Tree.Editor.zip)

**Comment by Richard01CZ** [comment]
[Cache Fucker v1.0.zip](https://github.com/user-attachments/files/16268030/Cache.Fucker.v1.0.zip)
[Cache.bin Editor.zip](https://github.com/user-attachments/files/16268032/Cache.bin.Editor.zip)
[CacheRE v1.1 + 1.2.zip](https://github.com/user-attachments/files/16268033/CacheRE.v1.1.%2B.1.2.zip)
[Capone 1.0d1.zip](https://github.com/user-attachments/files/16268034/Capone.1.0d1.zip)
[Car Changer v1.4.zip](https://github.com/user-attachments/files/16268035/Car.Changer.v1.4.zip)
[Car Index Editor.zip](https://github.com/user-attachments/files/16268038/Car.Index.Editor.zip)

**Comment by Richard01CZ** [comment]
[DCED2.zip](https://github.com/user-attachments/files/16268313/DCED2.zip)
[def2bbrd v0.5.zip](https://github.com/user-attachments/files/16268316/def2bbrd.v0.5.zip)
[DNC Extractor.zip](https://github.com/user-attachments/files/16268324/DNC.Extractor.zip)
[Dog Maker.zip](https://github.com/user-attachments/files/16268326/Dog.Maker.zip)
[Draw Distance Unlimiter.zip](https://github.com/user-attachments/files/16268327/Draw.Distance.Unlimiter.zip)
[DTA Unpacker (cline).zip](https://github.com/user-attachments/files/16268332/DTA.Unpacker.cline.zip)
[DTA Unpacker.zip](https://github.com/user-attachments/files/16268335/DTA.Unpacker.zip)
[DTAs Packer.zip](https://github.com/user-attachments/files/16268337/DTAs.Packer.zip)

**Comment by RoadTrain** [comment]
There's also my plugin for Noesis: https://github.com/RoadTrain/noesis-plugins 
And Boz's plugin for Blender https://github.com/djbozkosz/BlenderMafia4ds

**Comment by Richard01CZ** [comment]
[Effects.bin Editor.zip](https://github.com/user-attachments/files/16273701/Effects.bin.Editor.zip)
[Glow Maker.zip](https://github.com/user-attachments/files/16273702/Glow.Maker.zip)
[GmfRE v1.1.zip](https://github.com/user-attachments/files/16273703/GmfRE.v1.1.zip)
[Check.bin Editor EN+RU.zip](https://github.com/user-attachments/files/16273704/Check.bin.Editor.EN%2BRU.zip)
[CheckRE 1.3.zip](https://github.com/user-attachments/files/16273712/CheckRE.1.3.zip)
[CHG Editor v1.1 + v3.0.zip](https://github.com/user-attachments/files/16273713/CHG.Editor.v1.1.%2B.v3.0.zip)
[CHG Maker.zip](https://github.com/user-attachments/files/16273714/CHG.Maker.zip)

**Comment by Richard01CZ** [comment]
[LmapGen 2.zip](https://github.com/user-attachments/files/16315519/LmapGen.2.zip)
[LMToner v6.2.zip](https://github.com/user-attachments/files/16315521/LMToner.v6.2.zip)
[LS3D Lightmapper.zip](https://github.com/user-attachments/files/16315522/LS3D.Lightmapper.zip)
[LS3D Sandbox 2.zip](https://github.com/user-attachments/files/16315525/LS3D.Sandbox.2.zip)
[LS3D Sandbox.zip](https://github.com/user-attachments/files/16315526/LS3D.Sandbox.zip)

**Comment by Richard01CZ** [comment]
[M Editor v1.12.zip](https://github.com/user-attachments/files/16315588/M.Editor.v1.12.zip)
[Mafia Car Adder & Remover v0.62 (Beta).zip](https://github.com/user-attachments/files/16315591/Mafia.Car.Adder.Remover.v0.62.Beta.zip)
[Mafia Car Installer.zip](https://github.com/user-attachments/files/16315593/Mafia.Car.Installer.zip)
[Mafia Car Value Editor.zip](https://github.com/user-attachments/files/16315594/Mafia.Car.Value.Editor.zip)
[Mafia Editor (.def) v2.0.zip](https://github.com/user-attachments/files/16315596/Mafia.Editor.def.v2.0.zip)
[Mafia GetPos.zip](https://github.com/user-attachments/files/16315597/Mafia.GetPos.zip)

**Comment by Richard01CZ** [comment]
[Mafia Load Editor v1.0.zip](https://github.com/user-attachments/files/16315705/Mafia.Load.Editor.v1.0.zip)
[Mafia Script Helper v2.0.zip](https://github.com/user-attachments/files/16315706/Mafia.Script.Helper.v2.0.zip)
[Mafia Text Editor 1.0 + 1.1.zip](https://github.com/user-attachments/files/16315707/Mafia.Text.Editor.1.0.%2B.1.1.zip)
[Mafia Value Editor v0.0.6.81.zip](https://github.com/user-attachments/files/16315708/Mafia.Value.Editor.v0.0.6.81.zip)
[Mafia Weapon Editor.zip](https://github.com/user-attachments/files/16315709/Mafia.Weapon.Editor.zip)
[Mafia Weapon Value Editor.zip](https://github.com/user-attachments/files/16315710/Mafia.Weapon.Value.Editor.zip)

**Comment by Richard01CZ** [comment]
[noesis-plugins-master.zip](https://github.com/user-attachments/files/16315885/noesis-plugins-master.zip)
[BlenderMafia4ds-master.zip](https://github.com/user-attachments/files/16315886/BlenderMafia4ds-master.zip)

**Comment by Richard01CZ** [comment]
[Mafia World & Model Viewer v0.5.0.zip](https://github.com/user-attachments/files/16324868/Mafia.World.Model.Viewer.v0.5.0.zip)
[MafiaHack v1.03.zip](https://github.com/user-attachments/files/16324869/MafiaHack.v1.03.zip)
[MED (Facial Animation Editor).zip](https://github.com/user-attachments/files/16324870/MED.Facial.Animation.Editor.zip)
[MemSup v1.0a.zip](https://github.com/user-attachments/files/16324871/MemSup.v1.0a.zip)
[Menu.def Editor v1.00 (djboz).zip](https://github.com/user-attachments/files/16324872/Menu.def.Editor.v1.00.djboz.zip)
[Menu.def Editor.zip](https://github.com/user-attachments/files/16324873/Menu.def.Editor.zip)
[Metro and Salina Editor v1.1.zip](https://github.com/user-attachments/files/16324943/Metro.and.Salina.Editor.v1.1.zip)

**Comment by Richard01CZ** [comment]
[MEXED.zip](https://github.com/user-attachments/files/16324957/MEXED.zip)
[Mexer v1.1.zip](https://github.com/user-attachments/files/16324958/Mexer.v1.1.zip)
[MCHDSR v0.75.zip](https://github.com/user-attachments/files/16324959/MCHDSR.v0.75.zip)
[Orure v0.9.zip](https://github.com/user-attachments/files/16324987/Orure.v0.9.zip)
[Pos Tool.zip](https://github.com/user-attachments/files/16324961/Pos.Tool.zip)
[Predmety.def Editor.zip](https://github.com/user-attachments/files/16324963/Predmety.def.Editor.zip)
[RHAM Collection.zip](https://github.com/user-attachments/files/16324964/RHAM.Collection.zip)

**Comment by Richard01CZ** [comment]
[Camera Mod [R2].zip](https://github.com/user-attachments/files/16325025/Camera.Mod.R2.zip)
[Rmorf.bin Editor.zip](https://github.com/user-attachments/files/16325026/Rmorf.bin.Editor.zip)
[Road.bin Creator.zip](https://github.com/user-attachments/files/16325027/Road.bin.Creator.zip)

**Comment by Richard01CZ** [comment]
[Road.bin Editor.zip](https://github.com/user-attachments/files/16325116/Road.bin.Editor.zip)

**Comment by Richard01CZ** [comment]
[RoadRE v0.1.zip](https://github.com/user-attachments/files/16325123/RoadRE.v0.1.zip)

**Comment by Richard01CZ** [comment]
[Scena2 Editor 1.zip](https://github.com/user-attachments/files/16325141/Scena2.Editor.1.zip)
[Sound Maker.zip](https://github.com/user-attachments/files/16325146/Sound.Maker.zip)
[SSDM v1.0.zip](https://github.com/user-attachments/files/16325147/SSDM.v1.0.zip)
[Texture Resizer.zip](https://github.com/user-attachments/files/16325148/Texture.Resizer.zip)
[Zazona Modeler v1.07b + Patch.zip](https://github.com/user-attachments/files/16325149/Zazona.Modeler.v1.07b.%2B.Patch.zip)

[Shadow Generator.zip](https://github.com/user-attachments/files/16325145/Shadow.Generator.zip)

[SDPA 1.zip](https://github.com/user-attachments/files/16325144/SDPA.1.zip)
.zip)
[Scene2.bin Manager.zip](https://github.com/user-attachments/files/16325142/Scene2.bin.Manager.zip)
[SCn2 Tractor.zip](https://github.com/user-attachments/files/16325143/SCn2.Tractor.zip)

**Comment by Richard01CZ** [comment]
[3DS Max Import-Export Scripts.zip](https://github.com/user-attachments/files/16325185/3DS.Max.Import-Export.Scripts.zip)
[Mafia Patcher v1.2.0.zip](https://github.com/user-attachments/files/16325186/Mafia.Patcher.v1.2.0.zip)
[Blender 4ds Tools v0.0.3 [Test].zip](https://github.com/user-attachments/files/16325187/Blender.4ds.Tools.v0.0.3.Test.zip)
[Mafia Script Extensions v1.1.0.zip](https://github.com/user-attachments/files/16325188/Mafia.Script.Extensions.v1.1.0.zip)
[OCX Modules.zip](https://github.com/user-attachments/files/16325189/OCX.Modules.zip)

**Comment by Richard01CZ** [comment]
[ASI Loader - binkw32.zip](https://github.com/user-attachments/files/16325281/ASI.Loader.-.binkw32.zip)

**Comment by Richard01CZ** [comment]
[MafiaCon-v1.0.1.zip](https://github.com/user-attachments/files/16337671/MafiaCon-v1.0.1.zip)
Thanks to quarkblitz for this version

**Comment by Richard01CZ** [comment]
![MHlogo](https://github.com/user-attachments/assets/302d6c37-5b60-4d44-8804-9fb5fc59e83a)

**Comment by Richard01CZ** [comment]
[Mexer v1.1.zip](https://github.com/user-attachments/files/16404615/Mexer.v1.1.zip)
added english version and readmes

**Comment by RoadTrain** [comment]
> Za**z**o**n**a Modeler v1.07b + Patch.zip

Za**n**o**z**a :)

**Comment by Richard01CZ** [comment]
[Zanoza Modeler v1.07b + Patch.zip](https://github.com/user-attachments/files/16418271/Zanoza.Modeler.v1.07b.%2B.Patch.zip)

**Comment by Richard01CZ** [comment]
[CheckBIN.zip](https://github.com/user-attachments/files/21073868/CheckBIN.zip)
[MTE.zip](https://github.com/user-attachments/files/21073867/MTE.zip)

**Comment by Richard01CZ** [comment]
[Mafia 1.0 Plus.zip](https://github.com/user-attachments/files/22702558/Mafia.1.0.Plus.zip)

**Comment by Richard01CZ** [comment]
[MafiaVersionPatcher.zip](https://github.com/user-attachments/files/24266939/MafiaVersionPatcher.zip)
